core/task/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TimeField, DateField, SubmitField, SelectField
from wtforms.validators import DataRequired


class TaskForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    category = SelectField("Category", coerce=int, validators=[DataRequired()])
    date = DateField("Date", format="%Y-%m-%d", validators=[DataRequired()])
    time = TimeField("Time", format="%H:%M", validators=[DataRequired()])
    submit = SubmitField("Add task")

core/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__, template_folder="templates")

from . import views

core/home/views.py
from flask import render_template, flash
from flask_login import login_required, current_user
from ..models.todo import Todo
from ..models.todo import Category
from . import home
from datetime import datetime
from flask_jwt_extended import (
    jwt_required,
)


@home.route("/")
@jwt_required()
def homepage():
    no_of_Task_ID_Business = 0
    no_of_Task_ID_Personal = 0
    no_of_Task_ID_Other = 0
    todos = []
    try:
        user = current_user
        # Query todo table for todos linked to logged in user
        all_todos = Todo.query.filter_by(author=user).order_by(Todo.date).all()
        for todo in all_todos:
            todos.append(todo.to_dict())
        # Get current Date and Time
        date = datetime.now()
        # Format date to String
        now = date.strftime("%Y-%m-%d")
        # Format time to String
        currentTime = date.strftime("%H:%M")

        # Retrieve categories with their IDs
        category1 = Category.query.get(1)
        category2 = Category.query.get(2)
        category3 = Category.query.get(3)

        # Get each task under each category
        Task_ID_Business = Todo.query.filter_by(category=category1.name, author=user)
        Task_ID_Personal = Todo.query.filter_by(category=category2.name, author=user)
        Task_ID_Other = Todo.query.filter_by(category=category3.name, author=user)

        # Get the number of task under each category
        no_of_Task_ID_Business = Task_ID_Business.count()
        no_of_Task_ID_Personal = Task_ID_Personal.count()
        no_of_Task_ID_Other = Task_ID_Other.count()

    except Exception as e:
        return {"msg": "Loading homepage failed, please try again."}, 401

    response = {
        "todos": todos,
        "no_of_business_tasks": no_of_Task_ID_Business,
        "no_of_personal_tasks": no_of_Task_ID_Personal,
        "no_of_other_tasks": no_of_Task_ID_Other,
        "category_i_name": category1.name,
        "category_ii_name": category2.name,
        "category_iii_name": category3.name,
        "DateNow": now,
        "TimeNow": currentTime,
    }
    return response, 200

core/task/__init__.py
from flask import Blueprint

task = Blueprint("task", __name__, template_folder="templates")

from . import views

core/task/views.py
from flask import render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from ..models.todo import Todo, Category
from . import task
from .forms import TaskForm
from .. import db
from datetime import datetime
from flask_jwt_extended import (
    jwt_required,
)


@task.route("/delete_task", methods=["POST"])
@jwt_required()
def delete_task():
    # To delete a todo
    try:
        delete_task_id = request.json.get("task_id")
        # Deletes todo if checkbox is ticked
        if delete_task_id is not None:
            # Confirms actual todo with the ticked checkbox
            todo = Todo.query.filter_by(id=delete_task_id).first()
            if todo is None:
                return {"msg": "Please provide id of task to be deleted."}, 400

            db.session.delete(todo)
            db.session.commit()

        # To confirm if checkbox is ticked
        else:
            return {"msg": "Please provide id of task to be deleted."}, 400

    except Exception as e:
        db.session.rollback()
        return {"msg": "Task deletion failed, please try again."}, 400

    response = {
        "msg": "Task deleted successfully.",
    }
    return response, 200


@task.route("/get-todos/<user_id>", methods=["GET"])
@jwt_required()
def get_todos(user_id):
    todos = []
    # Query category table for categories linked to logged in user
    try:
        # Query todo table for todos linked to logged in user
        all_todos = Todo.query.filter_by(user_id=user_id).all()
        for todo in all_todos:
            todos.append(todo.to_dict())
    except Exception as e:
        return {"msg": "Failed to get todos."}, 400

    response = {
        "todos": todos,
    }
    return response, 200


@task.route("/get-categories", methods=["GET"])
@jwt_required()
def get_categories():
    categories = []
    # Query category table for categories linked to logged in user
    try:
        all_categories = Category.query.all()
        for category in all_categories:
            categories.append(category.to_dict())
    except Exception as e:
        return {"msg": "Failed to get categories."}, 400

    response = {
        "categories": categories,
    }
    return response, 200


@task.route("/create-task/<user_id>", methods=["GET", "POST"])
@jwt_required()
def create_task(user_id):
    title = request.json.get("title")
    date_string = request.json.get("date")
    time_string = request.json.get("time")
    selected_category_id = request.json.get("category_id")

    if title is None or title == "":
        return {"msg": "Title field is required"}, 400

    if selected_category_id is None or selected_category_id == "":
        return {"msg": "Category field is required"}, 400

    if date_string is None or date_string == "":
        return {"msg": "Date field is required"}, 400

    if time_string is None or time_string == "":
        return {"msg": "Time field is required"}, 400

    # Convert date string to date
    date = datetime.strptime(date_string, "%Y-%m-%d").date()
    # Convert time string to time
    time = datetime.strptime(time_string, "%H:%M").time()
    # To create a todo
    try:
        selected_category_id = selected_category_id
        category = Category.query.get(selected_category_id)
        todo = Todo(
            title=title,
            date=date,
            time=time,
            category=category.name,
            user_id=user_id,
        )
        db.session.add(todo)
        db.session.commit()

    except Exception as e:
        db.session.rollback()
        return {"msg": "Task creation failed, please try again."}, 400

    response = {
        "msg": "Congratulations, you just added a new task",
        "todo": todo.to_dict(),
    }
    return response, 201

core/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <!-- favicon -->
    <link
      rel="shortcut icon"
      href="{{url_for('static', filename='Logo.svg')}}"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
      integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    {% if request.url_rule.endpoint != 'index' 
      and request.url_rule.endpoint != 'auth.login' 
        and request.url_rule.endpoint != 'auth.register' %}
          <script src="{{ url_for('static', filename='sidebar.js') }}" defer></script>
    {% endif %} 
    
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>Todo List</title>
    {% endif %}
  </head>
  <body>
    <!-- This prevents the WRAPPER class from activating on the main, sign in and register pages -->
    {% if request.url_rule.endpoint != 'index' 
      and request.url_rule.endpoint != 'auth.login' 
        and request.url_rule.endpoint != 'auth.register' %}
          <div class="wrapper">
    {% endif %}

      <!-- This prevents the sidebar from showing up on the main, sign in and register pages -->
      {% if request.url_rule.endpoint != 'index' 
        and request.url_rule.endpoint != 'auth.login' 
          and request.url_rule.endpoint != 'auth.register' %} 
          {%include 'sidebar.html' %} 
      {% endif %}
      <!-- End of sidebar  -->
      {% block content %} {% endblock content%} 
      
      {% if request.url_rule.endpoint != 'index' 
        and request.url_rule.endpoint != 'auth.login' 
          and request.url_rule.endpoint != 'auth.register' %}
          </div>
      {% endif %}
  </body>
</html>

core/templates/home.html
{% extends "base.html" %} 

{% block content %}

<div class="main_content">
  <div class="welcome">
    <button id="openbutton" class="openbtn">&#9776;</button>
    <span class="welcome-text">
      Welcome <span class="user">{{current_user.username }}</span>
      <span class="exclamation-mark">!</span>
      <i class="fa fa-smile-o" aria-hidden="true"></i
    ></span>
    {% if no_of_other_tasks > 0 or no_of_business_tasks > 0 or
    no_of_personal_tasks > 0 %}
    <div class="taskAdd">
      <a href="{{url_for('task.manage_task')}}" class="btn btn-primary">
        <i class="fa fa-plus icon"></i> <span class="Add">Add</span>
        <span class="or">or</span> <i class="fa fa-trash-o icon"></i>
        <span class="Delete">Delete Task(s)</span>
      </a>
    </div>
    <!--end taskAdd -->
    {% endif %}
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
          <span class="closebtns" onclick="this.parentElement.style.display='none';"
            >&times;</span
          >{{message}}
        </div>
      {% endfor %} 
    {% endif %} 
  {% endwith %}

  <div class="category-card">
    <p class="heading">Overview</p>
    <div class="row">
      <div class="category category1">
        <span id="count"> {{no_of_business_tasks}} </span>
        <p><strong class="cat1"> {{category_i.name}} task(s)</strong></p>
      </div>
      <div class="vl"></div>
      <div class="category category2">
        <span id="count"> {{no_of_personal_tasks}} </span>
        <p><strong class="cat2">{{category_ii.name}} task(s)</strong></p>
      </div>
      <div class="vl"></div>
      <div class="category category3">
        <span id="count"> {{no_of_other_tasks}} </span>
        <p><strong class="cat3">{{category_iii.name}} task(s)</strong></p>
      </div>
    </div>
    <!--end row  -->
  </div>
  <div class="task-card">
    <p class="heading">Todo-List</p>
    <div class="tabs effect-1">
      <!-- radio buttons -->
      <input type="radio" id="tab-1" name="tab-effect-1" checked="checked" />
      <span>All</span>

      <input type="radio" id="tab-2" name="tab-effect-1" />
      <span>Pending</span>

      <input type="radio" id="tab-3" name="tab-effect-1" />
      <span>Overdue</span>

      <!-- end of radio buttons -->

      <!-- tab-content -->
      <div class="tab-content">
        <section id="tab-item-1">
          <ul class="taskList">
            {% for todo in todo %}
            <li class="currentTaskItem">
              <i class="fa fa-tasks" aria-hidden="true"></i>
              <span id="TaskDone" class="complete- taskDone"
                >{{ todo.title }}</span
              >
              <span class="taskDone">at</span>
              <strong class="taskDone"
                ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
              >
              <span class="taskDone">on</span>
              <strong class="taskDatee taskDone"
                ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
              >
              <span class="categoryy-{{ todo.category }}"
                >{{ todo.category }}</span
              >
            </li>
            {% endfor %}
          </ul>
          <!--end All-Tasks-List -->
        </section>
        <section id="tab-item-2">
          <ul id="currentTasks" class="taskList">
            {% for todo in todo %} 
              {% if todo.date.strftime('%Y-%m-%d') > DateNow %} 
                <li class="currentTaskItem">
                  <i class="fa fa-tasks" aria-hidden="true"></i>
                  <span id="TaskDone" class="complete- taskDone"
                    >{{ todo.title }}</span
                  >
                  <span class="taskDone">at</span>
                  <strong class="taskDone"
                    ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
                  >
                  <span class="taskDone">on</span>
                  <strong class="taskDatee taskDone"
                    ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
                  >
                  <span class="categoryy-{{ todo.category }}"
                    >{{ todo.category }}</span
                  >
                </li>
              {% endif %}
              {% if todo.date.strftime('%Y-%m-%d') == DateNow and todo.time.strftime('%H:%M') >= TimeNow %}
                <li class="currentTaskItem">
                  <i class="fa fa-tasks" aria-hidden="true"></i>
                  <span id="TaskDone" class="complete- taskDone"
                    >{{ todo.title }}</span
                  >
                  <span class="taskDone">at</span>
                  <strong class="taskDone"
                    ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
                  >
                  <span class="taskDone">on</span>
                  <strong class="taskDatee taskDone"
                    ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
                  >
                  <span class="categoryy-{{ todo.category }}"
                    >{{ todo.category }}</span
                  >
                </li>
              {% endif %} 
            {% endfor %}
          </ul>
          <!--end CurrentTaskList -->
        </section>
        <section id="tab-item-3">
          <ul id="overdueTasks" class="taskList">
            {% for todo in todo %} 
              {% if DateNow > todo.date.strftime('%Y-%m-%d') %}
                <li class="overdueTaskItem">
                  <i class="fa fa-tasks" aria-hidden="true"></i>
                  <span id="TaskDone" class="complete- taskDone"
                    >{{ todo.title }}</span
                  >
                  <span class="taskDone">at</span>
                  <strong class="taskDone"
                    ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
                  >
                  <span class="taskDone">on</span>
                  <strong class="taskDatee taskDone"
                    ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
                  >
                  <span class="categoryy-{{ todo.category }}"
                    >{{ todo.category }}</span
                  >
                </li>
              {% endif %}
              {% if DateNow == todo.date.strftime('%Y-%m-%d') and todo.time.strftime('%H:%M') < TimeNow %}
                <li class="overdueTaskItem">
                  <i class="fa fa-tasks" aria-hidden="true"></i>
                  <span id="TaskDone" class="complete- taskDone"
                    >{{ todo.title }}</span
                  >
                  <span class="taskDone">at</span>
                  <strong class="taskDone"
                    ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
                  >
                  <span class="taskDone">on</span>
                  <strong class="taskDatee taskDone"
                    ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
                  >
                  <span class="categoryy-{{ todo.category }}"
                    >{{ todo.category }}</span
                  >
                </li>
              {% endif %} 
            {% endfor %}
          </ul>
          <!--end OverdueTaskList -->
        </section>

        {% if no_of_other_tasks == 0 and no_of_business_tasks == 0 and
        no_of_personal_tasks == 0 %}
        <div class="No-task">
          <h2>No task yet</h2>
        </div>
        <div class="Addtask">
          <a href="{{url_for('task.manage_task')}}" class="btn btn-primary">
            <i class="fa fa-plus icon"></i>
            <span class="Add">Add Task(s) </span>
          </a>
        </div>
        <!--end Addtask -->
        {% endif %}
      </div>
    </div>
    {% if no_of_other_tasks > 0 or no_of_business_tasks > 0 or
    no_of_personal_tasks > 0 %}
    <div class="Addtask">
      <a href="{{url_for('task.manage_task')}}" class="btn btn-primary">
        <i class="fa fa-plus icon"></i>
      </a>
    </div>
    <!--end taskAdd -->
    {% endif %}
  </div>
</div>

{% endblock content %}

core/templates/index.html
{% extends "base.html" %}

{% block content %}


<div class="Home">

  <a class="brand-logo" href="{{ url_for('index') }}">
  <img class="logo" src="{{ url_for('static', filename='Logo.svg') }}">
  <div class="brand-logo-name"><strong> ToDo </strong> </div>
  </a>


  <div class="call-to-action">
      <h1 class="title">Achieve all your daily and weekly objectives in timely fashion <i class="fa fa-clock-o" aria-hidden="true"></i></h1>
      <h3 class="subtitle"> <strong>ToDo</strong> makes it easy to create and organize your tasks </h3>
      <a href="{{ url_for('auth.login') }}" class="btn">Let’s get started</a>
  </div>

</div>

{% endblock content %}

core/templates/login.html
{% extends "base.html" %} {% block content %}

<a class="brand-logo" href="{{ url_for('index') }}">
  <img class="logo" src="{{ url_for('static', filename='Logo.svg') }}" />
  <div class="brand-logo-name"><strong> ToDo </strong></div>
</a>


{% with messages = get_flashed_messages(with_categories=true) %} 
  {% if messages %} 
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        <span class="closebtns" onclick="this.parentElement.style.display='none';"
          >&times;</span
        >{{message}}
      </div>
    {% endfor %} 
  {% endif %} 
{% endwith %}

<div class="login">
  <form action="" method="post" novalidate class="p-3 border border-2">
    {{ form.hidden_tag() }}
    <div class="Login-Header">
      <h4 class="mb-5">Login</h4>
    </div>

    <p>
      {{ form.email.label }}<br />
      {{ form.email(size=32) }} {% for error in form.email.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>
      {{ form.password.label }}<br />
      {{ form.password(size=32) }} {% for error in form.password.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <div class="loginbtn">{{ form.submit(class="btn btn-primary mt-3") }}</div>
  </form>
  <div class="logged_in">
    <span>Dont have an account yet?</span>
    <a href="{{ url_for('auth.register') }}">
      <i class="fa fa-hand-o-right" aria-hidden="true"></i>Register</a
    >
  </div>
</div>
{% endblock %}

core/templates/register.html
{% extends "base.html" %} {% block content %}

<a class="brand-logo" href="{{ url_for('index') }}">
  <img class="logo" src="{{ url_for('static', filename='Logo.svg') }}" />
  <div class="brand-logo-name"><strong> ToDo </strong></div>
</a>

<div class="register">
  <form action="" method="post" class="p-3 border border-2">
    {{ form.hidden_tag() }}
    <div class="Register-Header">
      <h4 class="has-text-centered mb-5 is-size-3">Register</h4>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            <span class="closebtns" onclick="this.parentElement.style.display='none';"
              >&times;</span
            >{{message}}
          </div>
        {% endfor %} 
      {% endif %} 
    {% endwith %}
    
    <p>
      {{ form.username.label(class="label") }}
      <span style="color: red">*</span>
      <br />
      {{ form.username(size=32) }}<br />
      {% for error in form.username.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>
      {{ form.email.label(class="label") }}
      <span style="color: red">*</span>
      <br />
      {{ form.email(size=64) }}<br />
      {% for error in form.email.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>
      {{ form.password.label(class="label") }}
      <span style="color: red">*</span>
      <br />
      {{ form.password(size=32) }}<br />
      {% for error in form.password.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <p>
      {{ form.password2.label(class="label") }}
      <span style="color: red">*</span>
      <br />
      {{ form.password2(size=32) }}<br />
      {% for error in form.password2.errors %}
      <span style="color: red">[{{ error }}]</span>
      {% endfor %}
    </p>
    <div class="registerbtn">
      {{ form.submit(class="btn btn-primary mt-3") }}
    </div>
  </form>
  <div class="registered">
    <span>Already registered?</span>
    <a href="{{ url_for('auth.login') }}"
      ><i class="fa fa-hand-o-right" aria-hidden="true"></i>Login</a
    >
  </div>
</div>
{% endblock %}

core/templates/sidebar.html
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" id="closebutton" class="closebtn">&times;</a>
  <div class="top-sidebar">&nbsp;{{current_user.username}}'s Space</div>

  <ul>
    <li>
      <a
        class="{% if request.url_rule.endpoint == 'home.homepage' %} active {% endif %}"
        href="{{url_for('home.homepage')}}"
        ><i class="fa fa-home"></i>Home</a
      >
    </li>
    <li>
      <a
        class="{% if request.url_rule.endpoint == 'task.manage_task' %} active {% endif %}"
        href="{{url_for('task.manage_task')}}"
        ><i class="fa fa-tasks"></i>Task Management</a
      >
    </li>
    <li>
      <a href="{{url_for('auth.logout')}}"
        ><i class="fa fa-sign-out"></i>Logout</a
      >
    </li>
  </ul>
  <div class="social_media">
    <a href="https://www.linkedin.com/in/abdulsalam-saheed/"
      ><i class="fa fa-linkedin-square"></i
    ></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
  </div>
</div>

core/templates/tasks.html
{% extends "base.html" %} {% block content %}

<div class="task_content categories">
  <div class="">
    <div class="content">
      <div class="welcome">
        <button id="openbutton" class="openbtn">&#9776;</button>
        <span class="welcome-text">Manage Your ToDo List</span>
      </div>

      {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              <span class="closebtns" onclick="this.parentElement.style.display='none';"
                >&times;</span
              >{{message}}
            </div>
          {% endfor %} 
        {% endif %} 
      {% endwith %}

      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="inputContainer Task">
          <div>
            {{ form.title.label }}
            <span style="color: red">*</span>
          </div>
          <br />
          {{ form.title(size=20) }} {% for error in form.title.errors %}
          <span style="color: red">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="inputContainer choice">
          <div>
            {{ form.category.label}}
            <span style="color: red">*</span>
          </div>
          <br />
          {{ form.category}} {% for error in form.category.errors %}
          <span style="color: red">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="inputContainer date">
          <div>
            {{ form.date.label }}
            <span style="color: red">*</span>
          </div>
          <br />
          {{ form.date }} {% for error in form.date.errors %}
          <span style="color: red">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="inputContainer time">
          <div>
            {{ form.time.label }}
            <span style="color: red">*</span>
          </div>
          <br />
          {{ form.time }} {% for error in form.time.errors %}
          <span style="color: red">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="buttons">{{ form.submit(class="taskAdd btn") }}</div>
      </form>
      <!-- Task Delete Error alert -->
      {% if check %}
      <div class="alert alert-warning" role="alert">
        <span
          class="closebtns"
          onclick="this.parentElement.style.display='none';"
          >&times;</span
        >
        {{check}}
      </div>
      {% endif %}
      <!-- End Task Delete error alert -->

      {% for todo in todos %}
      <form action="{{url_for("task.delete_task")}}" method="post">
        {{ form.hidden_tag() }}
        <!-- csrf token for security -->

        <div class="tabs effect-1">
          <!-- tab-content -->
          <div class="tab-container">
            <section id="tab-item-1">
              <ul class="taskList">
                <li class="currentTaskItem">
                  <input
                    type="checkbox"
                    class="taskCheckbox"
                    name="checkedbox"
                    id="{{ todo.id }}"
                    value="{{ todo.id }}"
                  />
                  <label for="{{ todo.id }}"
                    ><span class="complete-">{{ todo.title }}</span></label
                  >
                  <span class="taskDone">at</span>
                  <strong class="taskDone"
                    ><i class="fa fa-clock-o"></i> {{ todo.time }}</strong
                  >
                  <span class="taskDone">on</span>
                  <strong class="taskDatee taskDone"
                    ><i class="fa fa-calendar"></i> {{ todo.date }}</strong
                  >
                  <span class="categorypage-{{ todo.category }}"
                    >{{ todo.category }}</span
                  >
                  <button
                    class="taskDelete"
                    name="taskDelete"
                    formnovalidate=""
                    type="submit"
                  >
                    <i class="fa fa-trash-o icon"></i>
                  </button>
                </li>
              </ul>
              <!--end All-Tasks-List -->
            </section>
          </div>
          <!-- end tab content -->
        </div>
        <!-- end tab effect -->
      </form>
      {% endfor %}
    </div>
    <!-- end content -->
  </div>
  <!-- container -->
</div>
{% endblock %}